<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <PlatformTarget>x86</PlatformTarget>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <ApplicationIcon>diogenes-256.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Be.Windows.Forms.HexBox" Version="1.6.1" />
    <PackageReference Include="J2534-Sharp" Version="1.0.0-CI00026" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="SecurityAccess\NativeUnlockDefinitions.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>NativeUnlockDefinitions.json</TargetPath>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Caesar\Caesar.csproj" />
  </ItemGroup>
</Project>
